//TODO: generate all routes here
const String LoginRoute = 'LoginRoute';
const String HomeViewRoute = 'HomeViewRoute';
const String NewAccountSuccessRoute = 'NewAccountSuccess';
const String SignUPViewRoute = 'SignupView';
const String StartupRoute = 'StartupView';
const String WelcomeRoute = 'WelcomeRoute';
const String ViewProfileViewRoute = 'ViewProfileView';
const String PhoneSignupViewRoute = 'PhoneSignUpView';
